name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow
      - dagshub
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
      - seaborn
      - joblib
      - kagglehub
